name: Check PR Source Branch

on:
  pull_request:
    branches:
      - main # Este workflow será executado para PRs direcionadas à 'main'

jobs:
  check_source_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if source branch is development
        run: |
          SOURCE_BRANCH="${{ github.head_ref }}" # Obtém o nome da branch de origem da PR
          TARGET_BRANCH="${{ github.base_ref }}" # Obtém o nome da branch de destino da PR

          echo "Source branch: $SOURCE_BRANCH"
          echo "Target branch: $TARGET_BRANCH"

          # Verifica se a branch de destino é 'main' E a branch de origem NÃO É 'development'
          if [[ "$TARGET_BRANCH" == "main" && "$SOURCE_BRANCH" != "development" ]]; then
            echo "Erro: Pull Request para 'main' deve vir apenas da branch 'development'."
            exit 1 # Falha o job, impedindo o merge
          else
            echo "Verificação da branch de origem aprovada."
          fi